// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	Image    *string             `json:"image,omitempty"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Admin     bool                `json:"admin"`
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        int                 `json:"id"`
	Image     *string             `json:"image,omitempty"`
	Name      string              `json:"name"`
}

// PostSignupJSONRequestBody defines body for PostSignup for application/json ContentType.
type PostSignupJSONRequestBody = SignUpRequest
